version: '2.1'
services:
  node0:
    build: .
    image: parity/3poa:stable
    command:
      --config /parity/config/node.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e   # Added enginer-signer as container argument to avoid 3 different node configuration files
      --dapps-interface 0.0.0.0
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
    ports:
      - 8545:8545
    volumes:
      - ./config/:/parity/config:ro
      - ./config/base_node0:/tmp/parity
    networks:
      app_net:
        ipv4_address: 172.16.0.10

  node1:
    build: .
    image: parity/3poa:stable
    command:
      --config /parity/config/node.toml
      --engine-signer 0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2
      --dapps-interface 0.0.0.0
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
    volumes:
      - ./config/:/parity/config
      - ./config/base_node1:/tmp/parity
    networks:
      app_net:
        ipv4_address: 172.16.0.11

  node2:
    build: .
    image: parity/3poa:stable
    command:
      --config /parity/config/node.toml
      --engine-signer 0x002e28950558fbede1a9675cb113f0bd20912019
      --dapps-interface 0.0.0.0
      --ws-interface 0.0.0.0
      --ui-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
    volumes:
      - ./config/:/parity/config
      - ./config/base_node2:/tmp/parity
    networks:
      app_net:
        ipv4_address: 172.16.0.12

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.100


  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000
    networks:
      app_net:
        ipv4_address: 172.16.0.200

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
        gateway: 172.16.0.1
